nodeLinker: pnp

packageExtensions:
  "@linaria/babel-preset@*":
    dependencies:
      "@babel/plugin-proposal-export-namespace-from": "*"
      "@babel/plugin-transform-modules-commonjs": "*"
  "@linaria/stylelint@*":
    peerDependencies:
      "@babel/core": "*"
  babel-plugin-jsx-dom-expressions@*:
    peerDependencies:
      "@babel/core": "*"
  babel-preset-solid@*:
    peerDependencies:
      "@babel/core": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.0-rc.5.cjs
