yarnPath: ".yarn/releases/yarn-berry.cjs"
packageExtensions:
  "@linaria/babel-preset@*":
    dependencies:
      "@babel/plugin-transform-modules-commonjs": "*"
      "@babel/plugin-proposal-export-namespace-from": "*"
  "@linaria/stylelint@*":
    peerDependencies:
      "@babel/core": "*"
  "@linaria/webpack-loader@*":
    peerDependencies:
      "@babel/core": "*"
      "webpack": "*"
