packageExtensions:
  "@linaria/babel-preset@*":
    dependencies:
      "@babel/plugin-proposal-export-namespace-from": "*"
      "@babel/plugin-transform-modules-commonjs": "*"
  "@linaria/stylelint@*":
    peerDependencies:
      "@babel/core": "*"
  "@linaria/webpack-loader@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-sources.cjs
