name: Test
on:
  push: {}
jobs:
  tests:
    strategy:
      matrix:
        step:
          - name: Lint
            command: pnpm lint
          - name: Typecheck
            command: pnpm typecheck
          - name: Unit tests
            command: pnpm test:unit
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: ${{ matrix.step.name }}
        run: ${{ matrix.step.command }}
