name: Test
on:
  push: {}
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare-env
      - name: Run linters
        run: yarn lint
  typecheck:
    name: Type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare-env
      - name: Check types
        run: yarn typecheck
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare-env
      - name: Run tests
        run: yarn unit-tests
